services:
  kachaka_project:
    image: v1-kachaka-jazzy:latest
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
    network_mode: host
    ipc: host
    privileged: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes: 
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../:/app/
    command: /app/docker/scripts/initialize-docker-container.sh
    stdin_open: true
    tty: true
    extra_hosts:
      - "display:host-gateway"

  novnc:
    image: theasp/novnc:latest
    profiles: ["darwin"]
    ports:
      - "8080:8080"  # Web interface port
      - "5900:5900"  # VNC port 
      - "6000:6000"  # X11 port
    restart: unless-stopped
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
